services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: amis
      POSTGRES_PASSWORD: amis
      POSTGRES_DB: amis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
